--- crates/arti-bench/Cargo.toml.orig	2022-02-05 18:36:07 UTC
+++ crates/arti-bench/Cargo.toml
@@ -21,7 +21,7 @@ serde_json = "1.0.50"
 tracing = "0.1.18"
 tracing-subscriber = { version = "0.3.0", features = ["env-filter"] }
 tokio = { version = "1.4", features = ["full"] }
-tor-rtcompat = { path="../tor-rtcompat", version = "0.0.4", features = ["tokio", "native-tls"] }
+tor-rtcompat = { path="../tor-rtcompat", version = "0.0.4", features = ["tokio", "rustls"] }
 arti-config = { path="../arti-config", version = "0.0.4"}
 arti-client = { package="arti-client", path = "../arti-client", version = "0.0.4"}
 tokio-socks = "0.5"
