--- crates/tor-chanmgr/Cargo.toml.orig	2022-02-05 18:39:41 UTC
+++ crates/tor-chanmgr/Cargo.toml
@@ -30,4 +30,4 @@ float_eq = "0.7"
 futures-await-test = "0.3.0"
 hex-literal = "0.3"
 tor-rtmock = { path="../tor-rtmock", version = "0.0.4"}
-tor-rtcompat = { path="../tor-rtcompat", version = "0.0.4", features=["tokio", "native-tls"] }
+tor-rtcompat = { path="../tor-rtcompat", version = "0.0.4", features=["tokio", "rustls"] }
