--- crates/arti/src/arti_defaults.toml.orig	2021-11-06 21:39:35 UTC
+++ crates/arti/src/arti_defaults.toml
@@ -38,7 +38,7 @@ trace_filter = "debug"
 #
 # The state directory is not yet used.
 [storage]
-cache_dir = "${APP_CACHE}"
+cache_dir = "/var/db/arti"
 state_dir = "${APP_LOCAL_DATA}"
 
 # Replacement values for consensus parameters.  This is an advanced option
