--- crates/arti-config/src/arti_defaults.toml.orig	2022-03-01 13:59:34 UTC
+++ crates/arti-config/src/arti_defaults.toml
@@ -61,7 +61,7 @@ console = "debug"
 #
 # The state directory is not yet used.
 [storage]
-cache_dir = "${ARTI_CACHE}"
+cache_dir = "/var/db/arti"
 state_dir = "${ARTI_LOCAL_DATA}"
 
 # Replacement values for consensus parameters.  This is an advanced option
