--- Cargo.toml.orig	2021-05-12 09:40:52 UTC
+++ Cargo.toml
@@ -66,7 +66,6 @@ multi-user = [ "basic-cookies", "jmespatch/sync", "reg
 functional-tests = []
 ui-tests = []
 extra-debug = [ "rpki/extra-debug" ]
-static-openssl = [ "openssl/vendored" ]
 
 # Make sure that Krill crashes on panics, rather than losing threads and
 # limping on in a bad state.
