--- Cargo.toml.orig	2021-06-29 23:43:34 UTC
+++ Cargo.toml
@@ -15,6 +15,7 @@ tui-unix = ["crosstermion/tui-react-termion", "tui-sha
 tui-crossplatform = ["crosstermion/tui-react-crossterm", "tui-shared"]
 
 tui-shared = ["tui", "tui-react", "open", "unicode-segmentation"]
+trash-move = ["trash"]
 
 [dependencies]
 clap = "3.0.0-beta.2"
@@ -27,7 +28,7 @@ num_cpus = "1.10.0"
 filesize = "0.2.0"
 anyhow = "1.0.31"
 colored = "2.0.0"
-trash = "2.0.1"
+trash = { version = "2.0.1", optional = true }
 
 # 'tui' related
 unicode-segmentation = { version = "1.3.0", optional = true }
