--- Cargo.toml.orig	2021-04-18 21:24:57 UTC
+++ Cargo.toml
@@ -46,9 +46,6 @@ features = ["derive"]
 predicates = "1.0.7"
 assert_cmd = "1.0.3"
 
-[features]
-vendored-openssl = ['openssl/vendored']
-
 [[bin]]
 path = "src/main.rs"
 name = "cargo-generate"
