--- Cargo.toml.orig	2022-06-06 15:39:26 UTC
+++ Cargo.toml
@@ -60,7 +60,7 @@ features = ['serde']
 
 [dependencies.mlua]
 version = "0.7.4"
-features = ['luajit', 'vendored', 'serialize', 'send']
+features = ['luajit', 'serialize', 'send']
 
 [dependencies.tui-input]
 version = "0.4.2"
